### ISSUE TITLE
Prevent window/tab titles starting with dash, like "- TopicFriends"

### ISSUE THREAD

**Issue by karol-depka** [karol-depka/NetworkingMatcher#93] opened 2018-03-24 22:49 UTC
E.g. on http://localhost:4444/profile

**Comment by moi-j** [comment] 2018-03-25 15:02
I cannot reproduce this issue

**Comment by moi-j** [comment] 2018-04-11 10:49
Closed by commit: 18e5f8be5da4c94aebd3553f0b44dec9626e2dbb

**Closed as completed by moi-j** 2018-04-11 10:49 UTC
